swagger: "2.0"

info:
  version: "0.1"
  title: Magnificent API
  description: User/Team/Account abstraction

basePath: /

consumes:
  - application/json
produces:
  - application/json

definitions:
  User:
    type: object
    properties:
      id:
        type: string
        example: npiccolotto
      name:
        type: string
        example: Nikolaus Piccolotto
      email:
        type: string
        example: npiccolotto@zalando.de
      realm:
        type: string
        example: employees
  CondensedUser:
    type: object
    properties:
      id:
        type: string
        example: npiccolotto
      realm:
        type: string
        example: employees
  Team:
    type: object
    properties:
      id:
        type: string
        example: stups
      full_name:
        type: string
        example: STUPS - STUPS To Unleash Penguin Swarms
      mail:
        type: array
        items:
          type: string
          example: stups@zalando.de
      members:
        type: array
        items:
          $ref: '#/definitions/CondensedUser'
      accounts:
        type: array
        items:
          $ref: '#/definitions/CondensedCloudAccount'
  CondensedTeam:
    type: object
    properties:
      id:
        type: string
        example: stups
      full_name:
        type: string
        example: STUPS - Penguin Swarms And More
  AuthorizationAction:
    type: object
    properties:
      policy:
        type: string
        example: radical-agility
      payload:
        type: object
        properties:
          # TODO use additionalProperties once swagger1st supports it
          team:
            type: string
            example: stups
  CloudAccount:
    type: object
    properties:
      id:
        type: string
        example: '1341351515'
      name:
        type: string
        example: stups
      disabled:
        type: boolean
        example: false
      type:
        type: string
        example: aws
      members:
        type: array
        items:
          $ref: '#/definitions/CondensedUser'
      owner:
        type: string
        example: stups
        description: The owning team
  CondensedCloudAccount:
    type: object
    properties:
      id:
        type: string
        example: '2553545114'
      type:
        type: string
        example: aws

parameters:
  UserRealm:
    description: The realm of a user
    type: string
    name: realm
    in: path
    required: true
  AccountType:
    description: The type of an account
    type: string
    name: type
    in: path
    required: true
  UserId:
    description: The user identifier
    type: string
    name: user
    in: path
    required: true
  AccountId:
    description: The account identifier
    type: string
    name: account
    in: path
    required: true
  TeamId:
    description: The team identifier
    type: string
    name: team
    in: path
    required: true
  AuthorizationRequest:
    description: The request to authorize
    schema:
      $ref: '#/definitions/AuthorizationAction'
    name: authrequest
    in: body
    required: true

paths:

  '/':
    get:
      summary: Application root
      operationId: org.zalando.stups.friboo.system.http/redirect-to-swagger-ui
      security:
        - oauth2: [uid]
      responses:
        default:
          description: "Redirects to /ui/"

  ## AUTH

  '/auth':
    get:
      summary: Request authorization to do something. User information is provided in Authorization header.
      operationId: org.zalando.stups.magnificent.api/get-auth
      security:
        - oauth2: [uid]
      parameters:
        - $ref: '#/parameters/AuthorizationRequest'
      responses:
        200:
          description: If request was granted
        403:
          description: If request was not granted

  ## USER

  '/users/{realm}/{user}':
    get:
      summary: Get information about a user
      operationId: org.zalando.stups.magnificent.api/get-user
      security:
        - oauth2: [uid]
      parameters:
        - $ref: '#/parameters/UserRealm'
        - $ref: '#/parameters/UserId'
      responses:
        200:
          description: Return user information
          schema:
            $ref: '#/definitions/User'
        404:
          description: If no such user exists

  '/users/self':
    get:
      summary: Get information about the user this token belongs to
      operationId: org.zalando.stups.magnificent.api/get-user-self
      security:
        - oauth2: [uid]
      responses:
        200:
          description: Return user information
          schema:
            $ref: '#/definitions/User'

  ## ACCOUNTS

  '/accounts/{type}':
    get:
      summary: List all accounts
      operationId: org.zalando.stups.magnificent.api/get-accounts
      security:
        - oauth2: [uid]
      parameters:
        - $ref: '#/parameters/AccountType'
        - name: user
          in: query
          type: string
          description: Only accounts where this user has access to
      responses:
        200:
          description: List of all cloud accounts
          schema:
            type: array
            items:
              $ref: '#/definitions/CloudAccount'
  '/accounts/{type}/{account}':
    get:
      summary: Get information about one account
      operationId: org.zalando.stups.magnificent.api/get-account
      security:
        - oauth2: [uid]
      parameters:
        - $ref: '#/parameters/AccountType'
        - $ref: "#/parameters/AccountId"
      responses:
        200:
          description: List one account
          schema:
            $ref: "#/definitions/CloudAccount"
        404:
          description: If no such account exists

  ## TEAMS

  '/teams':
    get:
      summary: List all teams
      operationId: org.zalando.stups.magnificent.api/get-teams
      security:
        - oauth2: [uid]
      parameters:
        - name: realm
          in: query
          type: string
          description: Realm for the "user" parameter
        - name: user
          in: query
          type: string
          description: Only teams where this user is a member
      responses:
        200:
          description: List all teams
          schema:
            type: array
            items:
              $ref: '#/definitions/CondensedTeam'
  '/teams/{team}':
    get:
      summary: Get information about one team
      operationId: org.zalando.stups.magnificent.api/get-team
      security:
        - oauth2: [uid]
      parameters:
        - $ref: "#/parameters/TeamId"
      responses:
        200:
          description: List one team
          schema:
            $ref: "#/definitions/Team"
        404:
          description: If no such team exists

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
